### ISSUE TITLE
Wieksza liczba urządzeń

### ISSUE THREAD

**Issue by MarekManiera** [bartekkois/GPONMonitor#1]
Witam,
Jak jest większą liczbę urządzeń OLT (w tym przypadku 16 sztuk), to niestety "zasłonięte" zostaje pole szukania osoby, a jest niezmiernie przydatne.
Proponuję w kodzie zmienić szerokość navibara by zwiększyć liczbę urządzeń do 2 wierszy a potem dopiero pole szukania.

![obraz](https://user-images.githubusercontent.com/30177334/28222203-afdd9984-68c6-11e7-9a9f-83a9c68da721.png)

**Comment by bartekkois** [comment]
Poprawiono w https://github.com/bartekkois/GPONMonitor/commit/f4b621cff77c47ea7b0b12035128e3bbab3320b2

**Comment by MarekManiera** [comment]
Po poprawce działa bardzo ładnie
dzięki
