### ISSUE TITLE
A new version of HALNY HL-1GE2 has appeared.

### ISSUE THREAD

**Issue by czmiel72** [bartekkois/GPONMonitor#12]
Hi
A new HALNY HL-1GE2 has appeared. Is there a chance to add support for it?

**Comment by bartekkois** [comment]
Where I can find the datasheet for this ONT?

**Comment by bartekkois** [comment]
Added in https://github.com/bartekkois/GPONMonitor/commit/7ff27af754994bb9c7165d268bbaab5f99c7d84a
