### ISSUE TITLE
Update Wiki for Debian 9

### ISSUE THREAD

**Issue by tdmadam** [bartekkois/GPONMonitor#16]
Please update the wiki for Debian 9 to make installation easier.
Here are the changes tested on two fresh installations of Debian 9 DVD

**Log in as 'su' as sudo users are not yet active**
`apt update && apt upgrade`

**Install the missing packages on a fresh installation of Debian 9 (debian-9.13.0-amd64-DVD-1)**
`apt install sudo apt-transport-https curl`

**Add 'username' to the sudo group**
`usermod -aG sudo username`

Reboot for changes to take effect

**Update to  aspnetcore-runtime-6.0
Add missing symbolic link to /usr/local/bin/dotnet**
```wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
wget -q https://packages.microsoft.com/config/debian/9/prod.list
sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
sudo apt-get update
sudo apt-get install aspnetcore-runtime-6.0
sudo ln -s /usr/bin/dotnet /usr/local/bin/dotnet
```

**Update to GPONMonitor-1.0.11.zip**
```
sudo mkdir -p /var/www_aspnetcore/GPONMonitor
cd /var/www_aspnetcore
curl -sSL -o GPONMonitor-1.0.11.zip https://github.com/bartekkois/GPONMonitor/releases/download/1.0.11/GPONMonitor-1.0.11.zip
sudo unzip GPONMonitor-1.0.11.zip -d /var/www_aspnetcore/GPONMonitor
```

**Comment by bartekkois** [comment]
I`ve updated the installation proces described in Wiki to Debian 11.
