### ISSUE TITLE
H640G does not display ethernet ports

### ISSUE THREAD

**Issue by kooziolm** [bartekkois/GPONMonitor#2]
H640G does not display ethernet ports.

**Comment by bartekkois** [comment]
Fixed in https://github.com/bartekkois/GPONMonitor/commit/28f2f76539e9d1332c21aea239bbddacad7f720d

**Comment by kooziolm** [comment]
Is it possible to add interfaces status.
![image](https://user-images.githubusercontent.com/27728362/30489127-b25c3476-9a36-11e7-8b47-663a97aab6e1.png)

Now I only see this information:

![image](https://user-images.githubusercontent.com/27728362/30489107-9de5770a-9a36-11e7-8a6f-2989c26907bc.png)

**Comment by bartekkois** [comment]
It should work however I dont't have this model to test it properly. Could you please:
- check using tcpdump what SNMP requests are sent to OLT when you refresh ONU state. There should be 4 pairs of requests with the following OIDs:
1.3.6.1.4.1.6296.101.23.6.1.1.1.5  // ETH port state (followed by OnuPortId, OnuId, 1 and PortNumber)
1.3.6.1.4.1.6296.101.23.6.1.1.1.8  // ETH port speed (followed by OnuPortId, OnuId, 1 and PortNumber)
- check using developer tools in your browser what does the API response with when you refresh ONU state (F12 > Network tab | then refresh ONU state | click on sth looking like this "?oltId=0&oltPortId=1&onuId=2" and check "Preview tab")

**Comment by kooziolm** [comment]
> check using tcpdump what SNMP requests are sent to OLT when you refresh ONU state. There should be 4 pairs of requests with the following OIDs:
1.3.6.1.4.1.6296.101.23.6.1.1.1.5 // ETH port state (followed by OnuPortId, OnuId, 1 and PortNumber)
1.3.6.1.4.1.6296.101.23.6.1.1.1.8 // ETH port speed (followed by OnuPortId, OnuId, 1 and PortNumber)
> 
The OISDs 1.3.6.1.4.1.6296.101.23.6.xxx request is not sent. For example, for model H660GW OIDs 1.3.6.1.4.1.6296.101.23.6.xxx are sent.

![image](https://user-images.githubusercontent.com/27728362/30494758-b1b52af6-9a49-11e7-808b-380e5fa728b9.png)
> check using developer tools in your browser what does the API response with when you refresh ONU state (F12 > Network tab | then refresh ONU state | click on sth looking like this "?oltId=0&oltPortId=1&onuId=2" and check "Preview tab")

> 
Response:
`{"oltId":3,"oltPortId":1,"oltOnuId":12,"modelType":{"value":"H640G","description":"H640G","severity":1},"descriptionName":{"value":"xxxx","description":"xxxx","severity":1},"gponSerialNumber":{"value":"xxxx","description":"xxxxx","severity":1},"gponProfile":{"value":"H640","description":"H640","severity":1},"opticalConnectionState":{"value":2,"description":"aktywne","severity":3},"opticalConnectionDeactivationReason":{"value":11,"description":"zamina na aktywny (administrator)","severity":3},"opticalPowerReceived":{"value":"-155","description":"-15,5 dBm","severity":3},"opticalCableDistance":{"value":502,"description":"502 m","severity":1},"opticalConnectionUptime":{"value":146715,"description":"1d 16:45:15","severity":1},"opticalConnectionInactiveTime":{"value":0,"description":"0d 00:00:00","severity":1},"systemUptime":{"value":146773,"description":"1d 16:46:13","severity":1},"blockStatus":{"value":255,"description":"brak blokady","severity":3},"blockReason":{"value":255,"description":"brak blokady","severity":3}}`

**Comment by bartekkois** [comment]
Are you sure you've synched all the changes in this commit https://github.com/bartekkois/GPONMonitor/commit/28f2f76539e9d1332c21aea239bbddacad7f720d before recompiling the app? 
What happen if you put a breakpoint in this line https://github.com/bartekkois/GPONMonitor/blob/a1a225521bc040d37f1e5ab9d210a5fc40c870c7/src/GPONMonitor/Models/Onu/H640GOnu.cs#L20 and refres ONU state?

**Comment by kooziolm** [comment]
Do not ask what I was doing wrong;). I did not have the latest revision. I had to put up a compilation environment for MVS 2017. Can you help me with the compilation? After compilation in the Release folder I only have this:
![image](https://user-images.githubusercontent.com/27728362/30514967-038db89e-9b20-11e7-88ae-204d5bffb2b2.png)

I do not have folder Runtime Refs and dll's files

**Comment by bartekkois** [comment]
You have to Publish the project to get GPONMonitor/bin/Release/PublishOutput folder with everyting you need (right click on the project in the Solution Explorer and choose Publish...).  
If you want to use the lates version you will also need to update the .NET Core to version 2.0.0 on your server (link: https://www.microsoft.com/net/core#linuxdebian).

**Comment by kooziolm** [comment]
Everything works, thank you very much for your support
![image](https://user-images.githubusercontent.com/27728362/30515608-b4670c96-9b2b-11e7-9774-a5102ced3bfa.png)

If you need me to test something write to me;)
