### ISSUE TITLE
GPO MONITOR PROBLEM 

### ISSUE THREAD

**Issue by infoserwis** [bartekkois/GPONMonitor#6]
Hi,
We have a problem with GPO MONITOR. We use dockerfiles. GPO MONITOR doesn't  work menu button on the phone

**Comment by bartekkois** [comment]
It is a problem related to the bug in jquery. Please check the latest 1.0.9 release.  You might need to clean the browser cache.

**Comment by infoserwis** [comment]
Thank you so much, problem have been closed
